export const GETHOMEDATA = "GETHOMEDATA"
export const GETEDHOMEDATA = "GETEDHOMEDATA"


export const GETSONGLIST = "GETSONGLIST"
export const GETEDSONGLIST = "GETEDSONGLIST"

export const GETSONGDETAIL = "GETSONGDETAIL"
export const GETEDSONGDETAIL = "GETEDSONGDETAIL"

export const TOGGLEPLAY = "TOGGLEPLAY"

export const SETSHOWLYRIC = "SETSHOWLYRIC"